name: camsvirtusa
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.5.3
  firebase_messaging: ^14.5.0
  google_fonts: ^6.1.0

  # State management
  provider: ^6.1.2

  # Icons
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

flutter_native_splash:
  color: "#FFFFFF"        # white background
  image: logo.png # your app logo (we’ll add this next)
  android: true
  ios: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Home.png"

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/role_top.png
    - assets/view_profile.png
    - assets/check_attendance.png
    - assets/on_duty.png
    - assets/leave_form.png
    - assets/mark_attendance.png
    - assets/student_details.png
    - assets/my_mentees.png
    - assets/student_ad.png
    - assets/staff_ad.png
    - assets/batch_ad.png
    - assets/department_ad.png
    - assets/timetable_ad.png
    - assets/Home.png
    - assets/college.png
    - assets/login_illustration.png
funding:
  -
dependency_overrides:
executables:
topics:
  -
documentation:
ignored_advisories: []
issue_tracker:
repository:
false_secrets:
  -
screenshots:
  -
homepage:
platforms:





